In [1]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[7,8,9],[4,5,6],[1,2,3]])
m=np.add(m1,m2)
print("after adding 2 matrices:\n",m)


after adding 2 matrices:
 [[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]


In [2]:
#2. Write a Python Program to Multiply Two Matrices?
import numpy as np
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[7,8,9],[4,5,6],[1,2,3]])
m=np.dot(m1,m2)
print("after multiplying 2 matrices:\n",m)


after multiplying 2 matrices:
 [[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


In [3]:
#3. Write a Python Program to Transpose a Matrix?
import numpy as np
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("transpose of matrix:\n",m1.T)

transpose of matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
l=list(map(str,input("enter the words: ").split()))
l.sort()
print("words after sorting in aplhabetical order\n",l)

enter the words: data science course machine learning
words after sorting in aplhabetical order
 ['course', 'data', 'learning', 'machine', 'science']


In [5]:
#5. Write a Python Program to Remove Punctuation From a String?
s=input("enter the string:\n ")
r=""
for i in s:
    if i.isalpha() or i.isdigit() or i==" ":
        r+=i
    else:
        continue
print("string after removing punctuations:\n",r)

enter the string:
 hello!!! world???---
string after removing punctuations:
 hello world
